baseURL = "https://suihan74.github.io/"
languageCode = "ja"
title = "すいはんぶろぐ.io"
theme = "github-style"
publishDir = "public"
googleAnalytics = "UA-71542625-2"
hasCJKLanguage = true

[params]
  author = "すいはん"
  description = "SNSよりも少し長い文を書くところ"
  github = "suihan74"
  twitter = "suihan742"
  mastodon = "https://pawoo.net/@suihan742"
  hatena = "suihan74"
  email = "suihan742あっとgmail.com"
  utterances = "suihan74/suihan74.github.io"
  avatar = "/images/author.png"
  url = "https://suihan74.github.io/"
  hugoRepository = "hugo_files"
  googleCSE = "006598476776954487838:x6qvcxfxgqt"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  archive = "archives"
