baseURL = "https://suihan74.github.io/"
languageCode = "ja"
title = "すいはんぶろぐ.io"
theme = "github-style"
publishDir = "public"
googleAnalytics = "UA-71542625-2"
hasCJKLanguage = true
pygmentsCodefences = true
pygmentsUseClasses = true
enableGitInfo = true

[params]
  author = "すいはん"
  description = "SNSよりも少し長い文を書くところ"
  keywords = ["ブログ","プログラミング","Android","kotlin","Hugo"]
  github = "suihan74"
  twitter = "suihan742"
  mastodon = "https://pawoo.net/@suihan742"
  hatena = "suihan74"
  email = "suihan742あっとgmail.com"
  utterances = "suihan74/suihan74.github.io"
  avatar = "/images/author.png"
  url = "https://suihan74.github.io/"
  hugoRepository = "hugo_files"
  googleCSE = "006598476776954487838:x6qvcxfxgqt"
  amazonAssociate = "suihan7406-22"
  disableDarkMode = true

[taxonomies]
  tag = "tags"
  archive = "archives"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = true
  disableXML = false

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
