baseURL = "https://suihan74.github.io/"
languageCode = "ja"
title = "すいはんぶろぐ.io"
theme = "github-style"
publishDir = "public"
googleAnalytics = "UA-71542625-2"

[params]
  author = "すいはん"
  description = "SNSよりも少し長い文を書くところ"
  github = "suihan74"
  twitter = "suihan742"
  mastodon = "https://pawoo.net/@suihan742"
  hatena = "suihan74"
  email = "suihan742あっとgmail.com"
  utterances = "suihan74.github.io"
  avatar = "https://avatars0.githubusercontent.com/u/5970984?s=460&v=4"
  url = "https://suihan74.github.io/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
