name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

    - name: Setup public repo
      run: |
          git clone --depth 1 https://suihan74:${{ secrets.MY_GITHUB_ACCESS_TOKEN }}@github.com/suihan74/suihan74.github.io.git public

    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version:
        # extended: true

    - name: Build
      run: |
          git submodule init
          git submodule update
          hugo --gc --minify --cleanDestinationDir
#           touch ./public/.nojekyll
#           cp ./CNAME ./public/

    - name: Deploy
      run: |
        export MSG=`git log --format=%B -n 1 HEAD`
        cd public
        git config --local user.name "suihan74"
        git config --local user.email "suihan742@gmail.com"
        git add .
        git commit -m "${MSG}"
        git push origin master

#    - name: Deploy
#      uses: peaceiris/actions-gh-pages@v2
#      env:
#        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#        EXTERNAL_REPOSITORY: suihan74/suihan74.github.io
#        PUBLISH_BRANCH: master
#        PUBLISH_DIR: ./public
